apiVersion: v1
kind: Pod
metadata:
  name: pod-deployment
  labels:
    app: pod-deployment
    type: front-end
spec:
  containers:
  - name: mynginx4
    image: subhadipdocker/exam:apacheexam4
---
apiVersion: v1
kind: Service
metadata:
  name: apacheservice
spec:
  type: NodePort
  selector:
    app: pod-deployment
    type: front-end
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
